const mongoose = require("mongoose");

// Application ID is now generated by the route handler using applicationIdGenerator.js
// Format: {TYPE}-{CATEGORY}-{YEAR}-{DEPT}-{SEQ}
// Example: F-NPT-2026-IT-001 (Faculty NPTEL 2026 IT Dept Sequence 1)

const FormSchema = new mongoose.Schema({
    applicationId: { type: String, unique: true, required: true }, // Generated by route
    userId: { type: String, required: true }, //link to postgres user_id
    name: { type: String, required: true },
    facultyId: { type: String }, // Faculty ID number
    email: { type: String, required: true },
    jobTitle: { type: String },
    department: { type: String }, // Department for HOD filtering
    academicYear: { type: String },
    amount: { type: Number },
    accountName: { type: String },
    ifscCode: { type: String },
    accountNumber: { type: String },
    courseName: { type: String, required: true }, // NPTEL Course Name for reimbursement
    marks: { type: Number, required: true }, // NPTEL course marks (0-100)
    reimbursementType: { type: String, default: "NPTEL" },
    applicantType: { type: String, default: "Faculty", enum: ["Faculty", "Coordinator", "HOD"] }, // Faculty, Coordinator, or HOD
    status: {
        type: String,
        default: "Under HOD",
        enum: ["Pending", "Under Coordinator", "Under HOD", "Under Principal", "Approved", "Reimbursed", "Disbursed", "Rejected"]
    },
    // Track which role rejected the application (for workflow visibility)
    rejectedBy: { type: String, enum: ["Coordinator", "HOD", "Principal", "Accounts", null], default: null },
    rejectionRemarks: { type: String }, // Reason for rejection
    remark: { type: String }, // Reviewer remark
    accountsComments: { type: String }, // Comments from Accounts department
    accountsRemarks: { type: String }, // Remarks from Accounts department
    reviewedBy: { type: String }, // Who reviewed (for Principal)
    reviewedAt: { type: Date }, // When reviewed
    documents: [
        {
            // Support both local file fields and Cloudinary fields
            filename: String,
            path: String,
            mimetype: String,
            url: String,
            publicId: String,
        },
    ],

}, { timestamps: true });

// Indexes for query performance on commonly filtered fields
FormSchema.index({ userId: 1 });
FormSchema.index({ status: 1 });
FormSchema.index({ department: 1 });
FormSchema.index({ status: 1, department: 1 }); // Compound: HOD queries filter by both
FormSchema.index({ status: 1, rejectedBy: 1 }); // Compound: rejected queries
FormSchema.index({ updatedAt: -1 }); // Sorting by latest update

module.exports = mongoose.model("Form", FormSchema);