const mongoose = require("mongoose");

// Application ID is now generated by the route handler using applicationIdGenerator.js
// Format: {TYPE}-{CATEGORY}-{YEAR}-{DEPT}-{SEQ}
// Example: F-NPT-2026-IT-001 (Faculty NPTEL 2026 IT Dept Sequence 1)

const FormSchema = new mongoose.Schema({
    applicationId: { type: String, unique: true, required: true }, // Generated by route
    userId: { type: String, required: true }, //link to postgres user_id
    name: { type: String, required: true },
    email: { type: String, required: true },
    jobTitle: { type: String },
    department: { type: String }, // Department for HOD filtering
    academicYear: { type: String },
    amount: { type: Number },
    accountName: { type: String },
    ifscCode: { type: String },
    accountNumber: { type: String },
    remark: { type: String },
    reimbursementType: { type: String, default: "NPTEL" },
    applicantType: { type: String, default: "Faculty", enum: ["Faculty", "Coordinator", "HOD"] }, // Faculty, Coordinator, or HOD
    status: {
        type: String,
        default: "Under HOD",
        enum: ["Pending", "Under Coordinator", "Under HOD", "Under Principal", "Approved", "Disbursed", "Rejected"]
    },
    documents: [
        {
            // Support both local file fields and Cloudinary fields
            filename: String,
            path: String,
            mimetype: String,
            url: String,
            publicId: String,
        },
    ],

}, { timestamps: true });

module.exports = mongoose.model("Form", FormSchema);