// models/StudentForm.js
const mongoose = require("mongoose");

// Application ID is now generated by the route handler using applicationIdGenerator.js
// Format: {TYPE}-{CATEGORY}-{YEAR}-{DEPT}-{SEQ}
// Example: S-NPT-2026-IT-001 (Student NPTEL 2026 IT Dept Sequence 1)

const StudentFormSchema = new mongoose.Schema({
    applicationId: { type: String, unique: true, required: true }, // Generated by route
    userId: { type: String, required: true }, // link to Postgres user_id
    name: { type: String, required: true },
    studentId: { type: String, required: true },
    division: { type: String, required: true },
    department: { type: String }, // Department for HOD filtering
    email: { type: String, required: true },
    academicYear: { type: String },
    amount: { type: Number },
    accountName: { type: String },
    ifscCode: { type: String },
    accountNumber: { type: String },
    courseName: { type: String, required: true }, // NPTEL Course Name for reimbursement
    marks: { type: Number, required: true }, // NPTEL course marks (0-100)
    reimbursementType: { type: String, default: "NPTEL" },
    status: { type: String, default: "Pending", enum: ["Pending", "Under Coordinator", "Under HOD", "Under Principal", "Approved", "Reimbursed", "Rejected"] },
    // Track which role rejected the application (for workflow visibility)
    rejectedBy: { type: String, enum: ["Coordinator", "HOD", "Principal", "Accounts", null], default: null },
    rejectionRemarks: { type: String }, // Reason for rejection
    documents: [
        {
            // Support both local file fields and Cloudinary fields
            filename: String,
            path: String,
            mimetype: String,
            url: String,
            publicId: String,
        },
    ],
}, { timestamps: true });

module.exports = mongoose.model("StudentForm", StudentFormSchema);